server:
  port: 8081

spring:
  application:
    name: price-ingestion
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topics:
      prices: prices
  binance:
    websocket-url: ${BINANCE_WEBSOCKET_URL:wss://stream.binance.com:9443/ws/btcusdt@ticker/ethusdt@ticker}
